apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        # This image path will be updated automatically by the pipeline
        image: asia-south1-docker.pkg.dev/verified-project-489808/java-project/java-app:latest
        ports:
        - containerPort: 8080
